In [10]:
import pandas as pd

In [11]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../scripts')))

In [12]:
from utils import *

In [13]:
csv_files = [
    '../data/scrapped_data/@CheMed123_data.csv',
    '../data/scrapped_data/@DoctorsET_data.csv',
    '../data/scrapped_data/@EAHCI_data.csv',
    '../data/scrapped_data/@lobelia4cosmetics_data.csv',
    '../data/scrapped_data/@yetenaweg_data.csv'
]

In [14]:
# Read each CSV into a DataFrame and store in a list
dfs = [pd.read_csv(file) for file in csv_files]

# Concatenate all DataFrames into one
merged_df = pd.concat(dfs, ignore_index=True)

# Save the merged DataFrame to a new CSV file
merged_df.to_csv('../data/scrapped_data/merged_file.csv', index=False)

In [15]:
merged_df.head()

,Channel Title,Channel Username,ID,Message,Date,Views,Message Link
0,CheMed,@CheMed123,97,"⚠️Notice!\nDear esteemed customers,\nDue to fo...",2023-02-10 12:23:06+00:00,1011.0,https://t.me/@CheMed123/97
1,CheMed,@CheMed123,96,Mela-One በውስጡ ሆርሞን ያለው ድንገተኛ ወሊድ መቆጣጠርያ ሲሆን ያለ...,2023-02-02 08:58:52+00:00,985.0,https://t.me/@CheMed123/96
2,CheMed,@CheMed123,95,አዚትሮማይሲን በሃኪም መድሃኒት ማዘዣ ከሚታዘዙ አንቲባዮቲኮች አንዱ ሲሆን...,2023-02-01 08:59:37+00:00,894.0,https://t.me/@CheMed123/95
3,CheMed,@CheMed123,94,Che-Med Trivia #3\n\nምግብና መጠጦች አንዳንድ መድሃኒቶች በደ...,2023-01-31 09:19:53+00:00,700.0,https://t.me/@CheMed123/94
4,CheMed,@CheMed123,93,"Che-Med Trivia #2\n\nእንደ Ciprofloxacin, Doxycy...",2023-01-30 09:45:25+00:00,612.0,https://t.me/@CheMed123/93

### Checking missing values

In [16]:
missing_values_table(merged_df)

Your selected dataframe has 7 columns.
There are 2 columns that have missing values.

         Missing Values  % of Total Values
Message            1189               18.7
Views               382                6.0

### Dropping missing values

In [17]:
merged_df.dropna(inplace=True)

In [18]:
missing_values_table(merged_df)

Your selected dataframe has 7 columns.
There are 0 columns that have missing values.

Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

### Checking for duplicates

In [19]:
# Check for duplicated rows
duplicated_rows = merged_df[merged_df.duplicated()]

# Display duplicated rows
duplicated_rows

Empty DataFrame
Columns: [Channel Title, Channel Username, ID, Message, Date, Views, Message Link]
Index: []

In [20]:
merged_df.shape

(5174, 7)

In [21]:
column_summary(merged_df)

,col_name,col_dtype,num_of_nulls,num_of_non_nulls,num_of_distinct_values,distinct_values_counts
0,Channel Title,object,0,5174,5,"{'Lobelia pharmacy and cosmetics': 2239, 'ETHI..."
1,Channel Username,object,0,5174,5,"{'@lobelia4cosmetics': 2239, '@EAHCI': 1536, '..."
2,ID,int64,0,5174,4183,"{71: 5, 57: 4, 58: 4, 70: 4, 40: 4, 39: 4, 10:..."
3,Message,object,0,5174,2874,{'NIDO USA 2.2KG Price 5900 birr Telegram htt...
4,Date,object,0,5174,3380,"{'2024-10-08 04:35:59+00:00': 24, '2024-10-02 ..."
5,Views,float64,0,5174,3038,"{1132.0: 10, 870.0: 9, 1050.0: 9, 857.0: 9, 11..."
6,Message Link,object,0,5174,5174,"{'https://t.me/@yetenaweg/4': 1, 'https://t.me..."

In [22]:
merged_df.columns

Index(['Channel Title', 'Channel Username', 'ID', 'Message', 'Date', 'Views',
       'Message Link'],
      dtype='object')

### Converting Some Object Data Types to String

In [23]:
columns_to_string = ["Channel Title", "Channel Username", "Message", "Message Link"]

In [24]:
for column in columns_to_string:
    merged_df[column] = merged_df[column].astype(str)

In [25]:
merged_df["Views"] = merged_df["Views"].astype(int)

### Converting Date Data Type to Pandas Date Time

In [26]:
merged_df["Date"] = pd.to_datetime(merged_df["Date"])

### Data Validation

In [27]:
!pip install emoji
import emoji


def remove_emojis(text):
    return emoji.replace_emoji(text, replace='')

merged_df["Message"] = merged_df["Message"].apply(remove_emojis)

Collecting emoji
  Downloading emoji-2.14.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.0-py3-none-any.whl (586 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 586.9/586.9 kB 1.3 MB/s eta 0:00:00a 0:00:01
Installing collected packages: emoji
Successfully installed emoji-2.14.0

In [28]:
merged_df.head()

,Channel Title,Channel Username,ID,Message,Date,Views,Message Link
0,CheMed,@CheMed123,97,"Notice!\nDear esteemed customers,\nDue to four...",2023-02-10 12:23:06+00:00,1011,https://t.me/@CheMed123/97
1,CheMed,@CheMed123,96,Mela-One በውስጡ ሆርሞን ያለው ድንገተኛ ወሊድ መቆጣጠርያ ሲሆን ያለ...,2023-02-02 08:58:52+00:00,985,https://t.me/@CheMed123/96
2,CheMed,@CheMed123,95,አዚትሮማይሲን በሃኪም መድሃኒት ማዘዣ ከሚታዘዙ አንቲባዮቲኮች አንዱ ሲሆን...,2023-02-01 08:59:37+00:00,894,https://t.me/@CheMed123/95
3,CheMed,@CheMed123,94,Che-Med Trivia #3\n\nምግብና መጠጦች አንዳንድ መድሃኒቶች በደ...,2023-01-31 09:19:53+00:00,700,https://t.me/@CheMed123/94
4,CheMed,@CheMed123,93,"Che-Med Trivia #2\n\nእንደ Ciprofloxacin, Doxycy...",2023-01-30 09:45:25+00:00,612,https://t.me/@CheMed123/93

In [29]:
column_summary(merged_df)

,col_name,col_dtype,num_of_nulls,num_of_non_nulls,num_of_distinct_values,distinct_values_counts
0,Channel Title,object,0,5174,5,"{'Lobelia pharmacy and cosmetics': 2239, 'ETHI..."
1,Channel Username,object,0,5174,5,"{'@lobelia4cosmetics': 2239, '@EAHCI': 1536, '..."
2,ID,int64,0,5174,4183,"{71: 5, 57: 4, 58: 4, 70: 4, 40: 4, 39: 4, 10:..."
3,Message,object,0,5174,2874,{'NIDO USA 2.2KG Price 5900 birr Telegram htt...
4,Date,"datetime64[ns, UTC]",0,5174,3380,"{2024-10-08 04:35:59+00:00: 24, 2024-10-02 08:..."
5,Views,int64,0,5174,3038,"{1132: 10, 870: 9, 1050: 9, 857: 9, 1170: 9, 1..."
6,Message Link,object,0,5174,5174,"{'https://t.me/@yetenaweg/4': 1, 'https://t.me..."

In [30]:
merged_df.to_csv('../data/scrapped_data/merged_file_cleaned.csv', index=False)